version: '3.7'

networks:
  dev:
    driver: bridge

services:
  client:
    build:
      context: ./WebNotesAPI.Web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  backend:
    depends_on:
      - "db"
    build:
      context: ./WebNotesAPI
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=Psibladeqqe13378;Server=db;Port=5433;Database=notesapp;Host=127.0.0.1;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8088:80"
    networks:
      - dev
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Psibladeqqe13378
      - POSTGRES_DB=notesapp
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:


